export const AUTH_TOKEN = 'AUTH_TOKEN';

export const CUSTOMER = 'CUSTOMER';
export const CHEF = 'CHEF';
export const SERVINGS_UNITS = ['grams', 'mill-litre', 'pieces', 'slices'];
export const PORTION_SIZES: Array<string> = [
  'full',
  'half',
  'large',
  'medium',
  'small',
  'standard',
];

// eslint-disable-next-line no-control-regex
export const EMAIL_PATTERN = /(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])/;

export const STATES: Array<string> = [
  'Andaman and Nicobar Islands',
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chandigarh',
  'Chhattisgarh',
  'Dadra and Nagar Haveli',
  'Daman and Diu',
  'Delhi',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jammu and Kashmir',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Lakshadweep',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Orissa',
  'Pondicherry',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Tripura',
  'Uttaranchal',
  'Uttar Pradesh',
  'West Bengal',
  'Telangana',
];
export const dishTypes: Array<string> = [
  'APPETIZERS',
  'BREAKFAST',
  'BEVERAGES',
  'BAKERY',
  'BURGERS',
  'COMBOS',
  'DESSERTS',
  'ENTREES',
  'PASTA',
  'OTHER',
  'PIZZA',
  'SALADS',
  'SNACKS',
  'SIDES',
  'SOUPS',
];
export const categories: Array<string> = [
  // "VEGERATARIAN",
  // "NON_VEG",
  // "VEGAN",
  // "DAIRY-FREE",
  '----',
  'DIABETIC-FRIENDLY',
  'GLUTEN-FREE',
  'LOW-CARB',
  'KETO',
];
export const cuisines: Array<string> = [
  'ALGERIAN',
  'AMERICAN',
  'BELGIAN',
  'BRAZILIAN',
  'BRITISH',
  'CAJUN',
  'CANADIAN',
  'CHINESE',
  'CUBAN',
  'EGYPTIAN',
  'FRENCH',
  'FUSION',
  'GERMAN',
  'GREEK',
  'HAITIAN',
  'HAWAIIAN',
  'INDIAN',
  'IRISH',
  'ITALIAN',
  'JAPANESE',
  'JEWISH',
  'KENYAN',
  'KOREAN',
  'LATVIAN',
  'LIBYAN',
  'MEXICAN',
  'MORMON',
  'NIGERIAN',
  'PERUVIAN',
  'POLISH',
  'PORTUGUESE',
  'SALADORIAN',
  'SCOTTISH',
  'SPANISH',
  'SWEDISH',
  'TAHITIAN',
  'THAI',
  'TIBETAN',
  'TURKISH',
  'WELSH',
];

export const ORDER_STATUSES = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  COMPLETED: 'COMPLETED',
  SUCCESS: 'SUCCESS',
  CANCELLED: 'CANCELLED',
};
